version: 1
services:
  - type: web
    name: erp-gateway
    runtime: docker
    dockerfilePath: gateway/Dockerfile
    rootDirectory: cloud-erp-platform
    plan: free
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /

  - type: static
    name: erp-dashboard
    staticPublishPath: ./cloud-erp-platform/dashboard
    buildCommand: echo "Static Dashboard"
    plan: free
